// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tracker.h"
#include <Rcpp.h>

using namespace Rcpp;

// track_here
void track_here();
RcppExport SEXP tracker_track_here() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    track_here();
    return R_NilValue;
END_RCPP
}
