// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tracker.h"
#include <Rcpp.h>

using namespace Rcpp;

// test_ProcessThreads
IntegerVector test_ProcessThreads();
RcppExport SEXP tracker_test_ProcessThreads() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_ProcessThreads());
    return __result;
END_RCPP
}
// test_ProcessThreadsPool
IntegerVector test_ProcessThreadsPool();
RcppExport SEXP tracker_test_ProcessThreadsPool() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_ProcessThreadsPool());
    return __result;
END_RCPP
}
