// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/tracker.h"
#include <Rcpp.h>

using namespace Rcpp;

// test_tracker
IntegerVector test_tracker();
RcppExport SEXP tracker_test_tracker() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_tracker());
    return __result;
END_RCPP
}
