# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_ProcessThreads <- function() {
    .Call('tracker_test_ProcessThreads', PACKAGE = 'tracker')
}

test_ProcessThreadsPool <- function() {
    .Call('tracker_test_ProcessThreadsPool', PACKAGE = 'tracker')
}

